### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HectorA6195** [AMPZNetwork/All-The-Forge-9#3]
**Describe the bug**
Unable to create Redstone using the create mod. The spout won't pour strength potion on the cinder flour to create Redstone,
The same setup will pour the potion into buckets and bottles.

**To Reproduce**
Fill a spout with strength potion and then place cinder flour on a depot underneath. Nothing will happen

**Expected behavior**
the spout is supposed to pour the strength potion on cinder flour to create redstone

**Basic Informations (please complete the following information):**
 - OS: Windows 10 Home
 - All The Forge 9 Version [1.8.0]
 - Platform [At Launcher]

**Comment by MasqueBleu** [comment]
Hello, im lunching ATF9 on CurseForge and it send me error 1 (i installed it via CursseForge)

**Comment by MasqueBleu** [comment]
Describe the bug
im lunching ATF9 on CurseForge and it send me error 1 (i installed it via CursseForge)

To Reproduce
Steps to reproduce the behavior:
Just lunch ATF9 on CurseForge lunch then on minecraft and Error 1.

Expected behavior
The game with ATF9 is suposed to start.

Basic Informations (please complete the following information):

OS: Windows 10 Home
All The Forge 9 Version [1.19.2-(43.2.14)]
Platform [At Launcher]
